export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  STOCK: '/stock',
  OPERATIONS: '/operations',
  DELIVERY_ORDERS: '/delivery-orders',
  DELIVERY_DETAIL: '/delivery-orders/:id',
  RECEIPTS: '/receipts',
  RECEIPT_DETAIL: '/receipts/:id',
  MOVE_HISTORY: '/move-history',
  SETTINGS: '/settings',
  WAREHOUSE_SETTINGS: '/settings/warehouse',
  LOCATION_SETTINGS: '/settings/location',
};
